function b = trfir1
%TRFIR1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 12-Apr-2021 15:23:25

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 119;  % Sampling Frequency
ration = Fs/200;

Fpass = 5*ration;                % Passband Frequency
Fstop = 20*ration;               % Stopband Frequency
Dpass = 0.057501127785;   % Passband Ripple
Dstop = 0.0031622776602;  % Stopband Attenuation
flag  = 'scale';          % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fpass Fstop]/(Fs/2), [1 0], [Dstop Dpass]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
%Hd = dfilt.dffir(b);

% [EOF]
